### PR TITLE
Fix tests and add GitHub Actions for CI

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
@johns31459 This PR adds GitHub Actions to run tests on PRs. You can see them running in my fork at https://github.com/mraible/foundry-sample-mitre/actions.

One question: it seems there is no `build` task in `shared/mitre-vue`, but there are tests. Is this expected since the components from this project are merely pulled in by the other projects? If so, I can adjust the CI process to only build the two projects under `ui`, and then run tests for all three projects.

**Comment by johns31459** [comment]
@mraible I imagine this is expected but I've pinged the original author of this project to check.

**Comment by giano** [comment]
@mraible yes, that would be a good step to add to have "fresh code" to test. Was not required at the time as apps were published manually.

**Comment by mraible** [comment]
@giano I've updated the CI process so it only compiles the ui projects and tests all three projects.

**Review by johns31459 — APPROVED** [review]

**Pull request merged**
